HTML Editor
mahavirvora/json-viewer pull request #4
Opened 2020-07-01 15:18 UTC by AshokPatel01

2020-07-03 05:47 UTC, mahavirvora requested changes
The assets folder should be outside of src.

2020-07-03 05:47 UTC, mahavirvora commented on package.json
> +    "jsoneditor": "^9.0.0",
Remove jquery & json editor

2020-07-03 16:14 UTC, AshokPatel01 commented on package.json
> +    "jsoneditor": "^9.0.0",
Removed

2020-07-09 13:38 UTC, AshokPatel01 commented
Screenshot: https://www.screencast.com/t/N45iiBhriNtH

2020-07-16 05:49 UTC, mahavirvora requested changes

2020-07-16 05:49 UTC, mahavirvora commented on angular.json
> +              "./node_modules/bootstrap/dist/css/bootstrap.css"
Keep "src/styles.scss"
remove bootstrap.css from here

2020-07-16 05:49 UTC, mahavirvora commented on package.json
> +    "@angular/localize": "^9.1.11",
Why are we adding this?

2020-07-16 05:49 UTC, mahavirvora commented on src/app/app.component.scss
> +@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap");
Move these imports to styles.scss file

2020-07-16 07:01 UTC, AshokPatel01 commented on angular.json
> +              "./node_modules/bootstrap/dist/css/bootstrap.css"
Updated as per comment.

2020-07-16 07:01 UTC, AshokPatel01 commented on package.json
> +    "@angular/localize": "^9.1.11",
Not required now.

2020-07-16 07:01 UTC, AshokPatel01 commented on src/app/app.component.scss
> +@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap");
Moved in style.scss

2020-07-23 06:01 UTC, merged